[package]
name = "oxide-ssh-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
async-channel.workspace = true
bytes.workspace = true
oxide-ssh-core.workspace = true
oxide-ssh-terminal.workspace = true
uuid.workspace = true
